## Numpy Arrays

In [1]:
import numpy as np
a=np.array([1,2,3,4,5,5,65,5])
a

array([ 1,  2,  3,  4,  5,  5, 65,  5])

In [11]:
b=np.zeros(7)
b

array([0., 0., 0., 0., 0., 0., 0.])

In [14]:
c=np.empty(2)
c

array([0., 0.])

In [18]:
d=np.ones(6)
d

array([1., 1., 1., 1., 1., 1.])

In [19]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [20]:
b=np.arange(6,15)
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
c=np.arange(3,42, 7)
c

array([ 3, 10, 17, 24, 31, 38])

In [30]:
d=np.linspace(0,10, num=9)
d

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [8]:
import numpy as np
a=np.zeros((3,3))
a


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])